name: Generate Articles

on:
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles to generate'
        required: true
        default: '1'
        type: number

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 137
        install-chromedriver: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    - name: Generate and Save Articles
      id: generate_articles
      env:
        DISPLAY: :99
        ARTICLE_COUNT: ${{ github.event.inputs.article_count }}
      run: |
        python scripts/generate_articles.py
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Add and Commit Changes
      run: |
        git add _posts embeddings
        git commit -m "feat(content): add generated articles and embeddings" || echo "No changes to commit"
    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}